### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by TheBassett** [blazsolar/HorizontalPicker#15]
When trying to implement this, it throws the following null pointer during run time (omitting everything not within this package):
"java.lang.NullPointerException
            at com.wefika.horizontalpicker.HorizontalPicker.startMarqueeIfNeeded(HorizontalPicker.java:876)
            at com.wefika.horizontalpicker.HorizontalPicker.calculateItemSize(HorizontalPicker.java:853)
            at com.wefika.horizontalpicker.HorizontalPicker.onSizeChanged(HorizontalPicker.java:441)"

My code is as follows:
![togithub](https://cloud.githubusercontent.com/assets/7651738/5870152/d6268722-a294-11e4-8ad6-a5552c8d07ae.PNG)

where "WheelNums" is:

![togithub2](https://cloud.githubusercontent.com/assets/7651738/5870156/e28dfa40-a294-11e4-8c50-6b4ee93a2934.PNG)

Also, I'm using version 1.0.1

I'm not sure if this is my fault or not, but feel free to correct me if it is!

PS - I believe your front page should read "xmlns:picker="http://schemas.android.com/apk/lib/com.wefika.horizontalpicker" " rather than "xmlns:picker="http://schemas.android.com/apk/res/com.wefika.horizontalpicker" " (lib vs res).

Thanks!
- Alex

**Comment by blazsolar** [comment]
This is fixed as part of issue #28
