### ISSUE TITLE
Null pointer on mTextColor

### ISSUE THREAD

**Issue by verbeeckjan** [blazsolar/HorizontalPicker#16]
When I try to open an activity that has the HorizontalPicker included I get the following error:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.res.ColorStateList.getDefaultColor()' on a null object reference
            at com.wefika.horizontalpicker.HorizontalPicker.getTextColor(HorizontalPicker.java:424)
            at com.wefika.horizontalpicker.HorizontalPicker.onDraw(HorizontalPicker.java:262)
```

I think it has something to do with using a custom style, but I don't know why exactly. It seems mTextColor is never set.

**Comment by blazsolar** [comment]
If you set text color for view issue will be solved.

I have also fixed the issue by setting default text color. It will be available in next release.
