### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by mcyrulik** [blazsolar/HorizontalPicker#17]
I've got one picker on the activity that when selected, populates another picker with values that depend on the selected item from the first picker. 

second picker is defined as follows:

    <com.wefika.horizontalpicker.HorizontalPicker
        xmlns:picker="http://schemas.android.com/apk/res/com.wefika.horizontalpicker"
        android:id="@+id/prod_category_picker"
        android:textColor="@color/light_gray"
        android:layout_below="@+id/prod_type_picker"
        android:layout_height="40dp"
        android:layout_width="match_parent"
        android:background="@color/slider_background"
        android:textSize="14sp"
        android:ellipsize="none"
        android:marqueeRepeatLimit="-1"
        android:visibility="gone"
        />
When I select an item in the first picker, intermittantly, I get this:

    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.RectF.set(android.graphics.RectF)' on a null object reference
            at com.wefika.horizontalpicker.HorizontalPicker.onDraw(HorizontalPicker.java:293)

I have not been able to figure out what sequence of events triggers this crash. Any thoughts?

**Comment by mcyrulik** [comment]
Just curious - do you have an idea of when you might look into this? 

Thanks

**Comment by blazsolar** [comment]
Hey,

sorry for not looking into this already, I have been quite busy. I'll try to look into it at the end of next week.

**Comment by blazsolar** [comment]
This should work in 1.1.0
