### ISSUE TITLE
No resource identifier found for attribute 'dividerSize' in package 'com.wefika.horizontalpicker'

### ISSUE THREAD

**Issue by Pavithrajas** [blazsolar/HorizontalPicker#23]
While running the application with the HorizontalPicker I am getting this error "Error:(33) No resource identifier found for attribute 'dividerSize' in package 'com.wefika.horizontalpicker'"

**Comment by Rishi91991** [comment]
Any Update?

**Comment by blazsolar** [comment]
Will check it sometime out this week

**Comment by blazsolar** [comment]
I was able to reproduce this issue when using `xmlns:app="http://schemas.android.com/apk/res/com.wefika.horizontalpicker"` schema. To resolve it just  change schema to `xmlns:app="http://schemas.android.com/apk/res-auto"` and it should work.

**Comment by Rishi91991** [comment]
Thanks mahn!!
