### ISSUE TITLE
Round item

### ISSUE THREAD

**Issue by bebethor** [blazsolar/HorizontalPicker#24]
Hello!!

How could I give this style to the horizontal picker?
![image](https://cloud.githubusercontent.com/assets/10145328/8980406/bcc1162a-36b0-11e5-94e8-b6edf09d104a.jpg)

I want round items instead rectangle ones. I this posible? thank you so much!!

**Comment by blazsolar** [comment]
No, this is not possible. At the moment `HorizontalPicker` accepts only text as input.

**Comment by bebethor** [comment]
Ok, Thank you!
