### ISSUE TITLE
No resource identifier found for attribute

### ISSUE THREAD

**Issue by hee4245** [blazsolar/HorizontalPicker#25]
Hi blazsolar,
I have a problem to use your nice library. I really need it.
I'm using android studio 1.3.
After import your library through gradle, I added your example code at xml.
When build my project, that error occurs.

Error:(43) No resource identifier found for attribute 'values' in package 'com.wefika.horizontalpicker'
Error:(43) No resource identifier found for attribute 'dividerSize' in package 'com.wefika.horizontalpicker'
Error:(43) No resource identifier found for attribute 'sideItems' in package 'com.wefika.horizontalpicker'

Is it still working xmlns:picker="http://schemas.android.com/apk/res/com.wefika.horizontalpicker"?
Please let me know how to solve this problem.

Thank you!

**Comment by ryanjohnstone** [comment]
I'm also having this issue, did you find a fix?

**Comment by justinwbriggs** [comment]
Also having this issue on 5.1

**Comment by blazsolar** [comment]
You should use `xmlns:app="http://schemas.android.com/apk/res-auto"` instead of `xmlns:picker="http://schemas.android.com/apk/res/com.wefika.horizontalpicker"`
