### ISSUE TITLE
Errore java.lang.NullPointerException: Attempt to read from null array & Rendering Problems

### ISSUE THREAD

**Issue by mpaloulack** [blazsolar/HorizontalPicker#28]
Hi, i have this problem with your library

first problem with layout : 

Missing styles. Is the correct theme chosen for this layout?  Use the Theme combo box above the layout to choose a different layout, or fix the theme style references.  Failed to find style 'horizontalPickerStyle' in current theme (2 similar errors not shown) onLayout error java.lang.NullPointerException   at com.wefika.horizontalpicker.HorizontalPicker.startMarqueeIfNeeded(HorizontalPicker.java:886)   at com.wefika.horizontalpicker.HorizontalPicker.calculateItemSize(HorizontalPicker.java:859)   at com.wefika.horizontalpicker.HorizontalPicker.onSizeChanged(HorizontalPicker.java:442)

and next problem

         java.lang.NullPointerException: Attempt to read from null array

but in my activity 

        HorizontalPicker test = (HorizontalPicker) findViewById(R.id.testPicker);

        List<String> listItems = new ArrayList<String>();

        listItems.add("Item1");
        listItems.add("Item2");
        listItems.add("Item3");

        final CharSequence[] charSequenceItems = listItems.toArray(new CharSequence[listItems.size()]);

        test.setSideItems(charSequenceItems.length);
        test.setValues(charSequenceItems);

in the logcat :: Caused by: java.lang.NullPointerException: Attempt to read from null array

    

thanks

**Comment by isuPatches** [comment]
Is there a release with this fix?

**Comment by blazsolar** [comment]
:+1:
