### ISSUE TITLE
how show two lines value 

### ISSUE THREAD

**Issue by AhmadVatani** [blazsolar/HorizontalPicker#32]
i want to show two line for values. for example in first line i want to put a string and below it i want to put an integer. how can i do that?? tnx

**Comment by blazsolar** [comment]
At the moment that is not possible. Implementation is based on [BoringLayout](http://developer.android.com/reference/android/text/BoringLayout.html) that only displays single line of text.

**Comment by AhmadVatani** [comment]
Can i ask when u will add this feature to your library??

**Comment by blazsolar** [comment]
At the moment this is out of the scope of this project.
