### ISSUE TITLE
Not working if put up in a Scroll View.

### ISSUE THREAD

**Issue by princebansal** [blazsolar/HorizontalPicker#33]
I am making a form where Horizontal  Picker will be basic form of input. There are multiple entries in the form and therefore I need to put them in a ScrollView. But as soon I put it in ScrollView, none of the element show up. I tried doing nestedScrolling enabled, but no luck. Please help urgently.

**Comment by blazsolar** [comment]
Hey,

I think solution for this is already on `develop` branch. I will try to release next version ASAP.
