### ISSUE TITLE
Change color of selected item

### ISSUE THREAD

**Issue by zunjae** [blazsolar/HorizontalPicker#36]
I don't know where to look since there is not much documentation, but how do I change the color of the item that is selected (or change the color of hte unset items)

Right now every item is the same color and the end user might not now which item is selected

**Comment by blazsolar** [comment]
Hi,

you can do that with color selector and then set ti via `android:textColor` xml property to picker.

Example of color selector:
https://github.com/blazsolar/HorizontalPicker/blob/develop/HorizontalPickerExample/src/main/res/color/text_color.xml
