### ISSUE TITLE
Items are not visible

### ISSUE THREAD

**Issue by vishalgupta1987** [blazsolar/HorizontalPicker#44]
I have added a Picker in layout as

<com.wefika.horizontalpicker.HorizontalPicker
            android:id="@+id/child_age_picker"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerVertical="true"
            android:ellipsize="none"
            android:marqueeRepeatLimit="-1"
            android:padding="8dp"
            android:textColor="@color/age_picker_text_color"
            android:textSize="14sp"
            app:dividerSize="8dp"
            app:sideItems="3"
            app:values="@array/child_ages" />

Picker is just drawn as blank while the items are in background scrolls  and event are also coming for selected items, but items are not visible

Please tell me the possible reasons for this issue.

**Comment by blazsolar** [comment]
What version are you using?
Is it inside of `ScrollView` or something similar?

**Comment by vishalgupta1987** [comment]
I am  using below details:

Picker Version
compile 'com.wefika:horizontal-picker:1.1.1'

Android SDK Versions
multiDexEnabled true
minSdkVersion 14
targetSdkVersion 23

View is not directly under scrollview but there is a scrollview in parent hierarchy. I have tested it without scrollview but still it is not showing

**Comment by vishalgupta1987** [comment]
I am able to identify the issue. hardwareAccelerated was set as false in Manisfest file.
android:hardwareAccelerated="false"_

Thanks
