### ISSUE TITLE
Selected item text color

### ISSUE THREAD

**Issue by reginatojames** [blazsolar/HorizontalPicker#56]
Howdy! Is it possible to change the selected item text color?

**Comment by webserveis** [comment]
I need same, how to change color when highlight selected

**Comment by blazsolar** [comment]
Hi, you can do that by setting selector as text color. You can see how to do that in example project included in source. https://github.com/blazsolar/HorizontalPicker/blob/develop/HorizontalPickerExample/src/main/res/color/text_color.xml

**Comment by reginatojames** [comment]
@blazsolar Uh, thank you so much, my bad for not noticing that in the example
